lang: c
env:
  - secure: "W5HYQoVpdUvDNYEqZUUnpv9dk3L8/pNaZkvES9klcv0SmI+RzM5II8fZicCU\nNtaSl0qkuiZVrVc/p9JZ+JxD7IXpjHI7MeGLS/KbuWS0XlR0yYASslBVnhIy\nUatXh/vZp5K2+gX9kLQq+IYNx41qI/Lrtw/mOrKEK05OBsPUn/U="
script: ./travis-ci.sh
#notifications:
#  irc:
#    - "irc.freenode.org#rerun"
