lang: c
env:
  - secure: "B8FHkDk+gjjNXC2uavWeBvk+mq0XENMYxC74cgoDVzYENjVooiCSMc1bnywH\nl50smH4RsEkKSlW2y8KgHdIlwjdt0SUd0dUoGH7eD3MzjZ8EWzI83kB8Lpbv\nUqnUpIKDiFA5g3BEOuc5g+rnDNQhHH94NRIdw02Tpn21eqBCp8I="
script: ./travis-ci.sh
#notifications:
#  irc:
#    - "irc.freenode.org#rerun"
