lang: c
env:
  - secure: "ruk3Y44NLSdmebmmGA5JG+MT+haDYpt9ysKu8bXYyiEjj0zqff3p2mrLvdyr\nENeU7d+qYLv0/86t7ROjxD4FWe2q5wF19w4OVbXDqTaisWAkvRPbeU3opFSQ\nXBhIu8x7Ht1psxL2YqY1vetDNe9TOLh5kOTpip31G42Pk7RVoMg="
script: ./travis-ci.sh
#notifications:
#  irc:
#    - "irc.freenode.org#rerun"
