lang: c
env:
  - secure: "mGUaDsv0eW5qMKq1y30YTus7rnu6UT9i87iV/27UDf3mUIYfBUEHbN3lE0ER\nglYA4iwBQW2UgQB+Fiqbbf3VyUUG/vJJkGrhNaXsBDVLtf3FuQ6OAlR0O3Sc\nlCgtQwOzJLWY6kMcd+u8pHT9xdzxODs0C+H6vg763Yscc/ZCB7M="
script: ./travis-ci.sh
#notifications:
#  irc:
#    - "irc.freenode.org#rerun"
